// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth.proto

package eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blockchain struct {
	NumberSize           string         `protobuf:"bytes,1,opt,name=numberSize,proto3" json:"numberSize,omitempty"`
	Hash                 string         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           string         `protobuf:"bytes,3,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	Nonce                string         `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sha3Uncles           string         `protobuf:"bytes,5,opt,name=sha3Uncles,proto3" json:"sha3Uncles,omitempty"`
	LogsBloom            string         `protobuf:"bytes,6,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	TransactionsRoot     string         `protobuf:"bytes,7,opt,name=transactionsRoot,proto3" json:"transactionsRoot,omitempty"`
	StateRoot            string         `protobuf:"bytes,8,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	ReceiptsRoot         string         `protobuf:"bytes,9,opt,name=receiptsRoot,proto3" json:"receiptsRoot,omitempty"`
	Miner                string         `protobuf:"bytes,10,opt,name=miner,proto3" json:"miner,omitempty"`
	Difficulty           string         `protobuf:"bytes,11,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	TotalDifficulty      string         `protobuf:"bytes,12,opt,name=totalDifficulty,proto3" json:"totalDifficulty,omitempty"`
	ExtraData            string         `protobuf:"bytes,13,opt,name=extraData,proto3" json:"extraData,omitempty"`
	Size                 string         `protobuf:"bytes,14,opt,name=size,proto3" json:"size,omitempty"`
	GasLimit             string         `protobuf:"bytes,15,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed              string         `protobuf:"bytes,16,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Timestamp            string         `protobuf:"bytes,17,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,18,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Uncles               []string       `protobuf:"bytes,19,rep,name=uncles,proto3" json:"uncles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Blockchain) Reset()         { *m = Blockchain{} }
func (m *Blockchain) String() string { return proto.CompactTextString(m) }
func (*Blockchain) ProtoMessage()    {}
func (*Blockchain) Descriptor() ([]byte, []int) {
	return fileDescriptor_d980f775760351f6, []int{0}
}

func (m *Blockchain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blockchain.Unmarshal(m, b)
}
func (m *Blockchain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blockchain.Marshal(b, m, deterministic)
}
func (m *Blockchain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blockchain.Merge(m, src)
}
func (m *Blockchain) XXX_Size() int {
	return xxx_messageInfo_Blockchain.Size(m)
}
func (m *Blockchain) XXX_DiscardUnknown() {
	xxx_messageInfo_Blockchain.DiscardUnknown(m)
}

var xxx_messageInfo_Blockchain proto.InternalMessageInfo

func (m *Blockchain) GetNumberSize() string {
	if m != nil {
		return m.NumberSize
	}
	return ""
}

func (m *Blockchain) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Blockchain) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (m *Blockchain) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Blockchain) GetSha3Uncles() string {
	if m != nil {
		return m.Sha3Uncles
	}
	return ""
}

func (m *Blockchain) GetLogsBloom() string {
	if m != nil {
		return m.LogsBloom
	}
	return ""
}

func (m *Blockchain) GetTransactionsRoot() string {
	if m != nil {
		return m.TransactionsRoot
	}
	return ""
}

func (m *Blockchain) GetStateRoot() string {
	if m != nil {
		return m.StateRoot
	}
	return ""
}

func (m *Blockchain) GetReceiptsRoot() string {
	if m != nil {
		return m.ReceiptsRoot
	}
	return ""
}

func (m *Blockchain) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *Blockchain) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *Blockchain) GetTotalDifficulty() string {
	if m != nil {
		return m.TotalDifficulty
	}
	return ""
}

func (m *Blockchain) GetExtraData() string {
	if m != nil {
		return m.ExtraData
	}
	return ""
}

func (m *Blockchain) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Blockchain) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *Blockchain) GetGasUsed() string {
	if m != nil {
		return m.GasUsed
	}
	return ""
}

func (m *Blockchain) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Blockchain) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Blockchain) GetUncles() []string {
	if m != nil {
		return m.Uncles
	}
	return nil
}

type Transaction struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d980f775760351f6, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Blockchain)(nil), "eth.Blockchain")
	proto.RegisterType((*Transaction)(nil), "eth.Transaction")
}

func init() { proto.RegisterFile("eth.proto", fileDescriptor_d980f775760351f6) }

var fileDescriptor_d980f775760351f6 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xb5, 0xb4, 0xdb, 0xdd, 0x4c, 0xbb, 0x6c, 0x31, 0x08, 0x59, 0x08, 0xa1, 0xaa, 0xa7,
	0x88, 0x43, 0x82, 0x58, 0x9e, 0xa0, 0xda, 0x03, 0x07, 0x4e, 0x81, 0xbd, 0x70, 0x73, 0xdc, 0xd9,
	0xd8, 0xc2, 0x7f, 0xa2, 0x78, 0x22, 0x01, 0x0f, 0xca, 0xf3, 0x20, 0xdb, 0x90, 0xb4, 0x70, 0xf3,
	0xfc, 0xbe, 0x6f, 0xc6, 0x9e, 0xf1, 0x40, 0x81, 0xa4, 0xaa, 0x7e, 0xf0, 0xe4, 0xd9, 0x02, 0x49,
	0xed, 0x7f, 0x2d, 0x01, 0x0e, 0xc6, 0xcb, 0x6f, 0x52, 0x09, 0xed, 0xd8, 0x1b, 0x00, 0x37, 0xda,
	0x16, 0x87, 0xcf, 0xfa, 0x27, 0xf2, 0x8b, 0xdd, 0x45, 0x59, 0x34, 0x27, 0x84, 0x31, 0x58, 0x2a,
	0x11, 0x14, 0x7f, 0x92, 0x94, 0x74, 0x8e, 0x39, 0xbd, 0x18, 0xd0, 0xd1, 0xc7, 0xa8, 0x2c, 0x72,
	0xce, 0x4c, 0xd8, 0x0b, 0xb8, 0x74, 0xde, 0x49, 0xe4, 0xcb, 0x24, 0xe5, 0x20, 0x66, 0x05, 0x25,
	0xee, 0x1e, 0x9c, 0x34, 0x18, 0xf8, 0x65, 0xce, 0x9a, 0x09, 0x7b, 0x0d, 0x85, 0xf1, 0x5d, 0x38,
	0x18, 0xef, 0x2d, 0x5f, 0x25, 0x79, 0x06, 0xec, 0x2d, 0x6c, 0x69, 0x10, 0x2e, 0x08, 0x49, 0xda,
	0xbb, 0xd0, 0x78, 0x4f, 0xfc, 0x2a, 0x99, 0xfe, 0xe3, 0xb1, 0x52, 0x20, 0x41, 0x98, 0x4c, 0xd7,
	0xb9, 0xd2, 0x04, 0xd8, 0x1e, 0x36, 0x03, 0x4a, 0xd4, 0x3d, 0xe5, 0x2a, 0x45, 0x32, 0x9c, 0xb1,
	0xd8, 0x81, 0xd5, 0x0e, 0x07, 0x0e, 0xb9, 0x83, 0x14, 0xc4, 0x0e, 0x8e, 0xfa, 0xf1, 0x51, 0xcb,
	0xd1, 0xd0, 0x0f, 0xbe, 0xce, 0x1d, 0xcc, 0x84, 0x95, 0x70, 0x4b, 0x9e, 0x84, 0xb9, 0x9f, 0x4d,
	0x9b, 0x64, 0xfa, 0x17, 0xc7, 0x17, 0xe2, 0x77, 0x1a, 0xc4, 0xbd, 0x20, 0xc1, 0x6f, 0xf2, 0x0b,
	0x27, 0x10, 0x67, 0x1e, 0xe2, 0x6f, 0x3c, 0xcd, 0x33, 0x8f, 0x67, 0xf6, 0x0a, 0xae, 0x3b, 0x11,
	0x3e, 0x69, 0xab, 0x89, 0xdf, 0x26, 0x3e, 0xc5, 0x8c, 0xc3, 0x55, 0x27, 0xc2, 0x43, 0xc0, 0x23,
	0xdf, 0x26, 0xe9, 0x6f, 0x18, 0xef, 0x21, 0x6d, 0x31, 0x90, 0xb0, 0x3d, 0x7f, 0x96, 0xef, 0x99,
	0x00, 0xfb, 0x00, 0x9b, 0xd3, 0xd9, 0x71, 0xb6, 0x5b, 0x94, 0xeb, 0xf7, 0xdb, 0x2a, 0x6e, 0xcc,
	0x97, 0x59, 0x68, 0xce, 0x5c, 0xec, 0x25, 0xac, 0xc6, 0xfc, 0x87, 0xcf, 0x77, 0x8b, 0xb2, 0x68,
	0xfe, 0x44, 0xfb, 0x1b, 0x58, 0x9f, 0x24, 0x1d, 0xde, 0x7d, 0xad, 0x3a, 0x4d, 0x6a, 0x6c, 0x2b,
	0xe9, 0x6d, 0xdd, 0xc6, 0x8d, 0xd3, 0x2e, 0xe8, 0x4e, 0x51, 0x6d, 0xfd, 0x11, 0x4d, 0xde, 0xc9,
	0xba, 0xf3, 0x46, 0xb8, 0xae, 0x46, 0x52, 0xed, 0x2a, 0x91, 0xbb, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x75, 0x05, 0xde, 0x70, 0xb2, 0x02, 0x00, 0x00,
}
