// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth/eth.proto

package eth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blockchain struct {
	NumberSize           string         `protobuf:"bytes,1,opt,name=numberSize,proto3" json:"numberSize,omitempty"`
	Hash                 string         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           string         `protobuf:"bytes,3,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	Nonce                string         `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sha3Uncles           string         `protobuf:"bytes,5,opt,name=sha3Uncles,proto3" json:"sha3Uncles,omitempty"`
	LogsBloom            string         `protobuf:"bytes,6,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	TransactionsRoot     string         `protobuf:"bytes,7,opt,name=transactionsRoot,proto3" json:"transactionsRoot,omitempty"`
	StateRoot            string         `protobuf:"bytes,8,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	ReceiptsRoot         string         `protobuf:"bytes,9,opt,name=receiptsRoot,proto3" json:"receiptsRoot,omitempty"`
	Miner                string         `protobuf:"bytes,10,opt,name=miner,proto3" json:"miner,omitempty"`
	Difficulty           string         `protobuf:"bytes,11,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	TotalDifficulty      string         `protobuf:"bytes,12,opt,name=totalDifficulty,proto3" json:"totalDifficulty,omitempty"`
	ExtraData            string         `protobuf:"bytes,13,opt,name=extraData,proto3" json:"extraData,omitempty"`
	Size                 string         `protobuf:"bytes,14,opt,name=size,proto3" json:"size,omitempty"`
	GasLimit             string         `protobuf:"bytes,15,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed              string         `protobuf:"bytes,16,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Timestamp            string         `protobuf:"bytes,17,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,18,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Uncles               []string       `protobuf:"bytes,19,rep,name=uncles,proto3" json:"uncles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Blockchain) Reset()         { *m = Blockchain{} }
func (m *Blockchain) String() string { return proto.CompactTextString(m) }
func (*Blockchain) ProtoMessage()    {}
func (*Blockchain) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40374cd18fa609d, []int{0}
}

func (m *Blockchain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blockchain.Unmarshal(m, b)
}
func (m *Blockchain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blockchain.Marshal(b, m, deterministic)
}
func (m *Blockchain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blockchain.Merge(m, src)
}
func (m *Blockchain) XXX_Size() int {
	return xxx_messageInfo_Blockchain.Size(m)
}
func (m *Blockchain) XXX_DiscardUnknown() {
	xxx_messageInfo_Blockchain.DiscardUnknown(m)
}

var xxx_messageInfo_Blockchain proto.InternalMessageInfo

func (m *Blockchain) GetNumberSize() string {
	if m != nil {
		return m.NumberSize
	}
	return ""
}

func (m *Blockchain) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Blockchain) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (m *Blockchain) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Blockchain) GetSha3Uncles() string {
	if m != nil {
		return m.Sha3Uncles
	}
	return ""
}

func (m *Blockchain) GetLogsBloom() string {
	if m != nil {
		return m.LogsBloom
	}
	return ""
}

func (m *Blockchain) GetTransactionsRoot() string {
	if m != nil {
		return m.TransactionsRoot
	}
	return ""
}

func (m *Blockchain) GetStateRoot() string {
	if m != nil {
		return m.StateRoot
	}
	return ""
}

func (m *Blockchain) GetReceiptsRoot() string {
	if m != nil {
		return m.ReceiptsRoot
	}
	return ""
}

func (m *Blockchain) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *Blockchain) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *Blockchain) GetTotalDifficulty() string {
	if m != nil {
		return m.TotalDifficulty
	}
	return ""
}

func (m *Blockchain) GetExtraData() string {
	if m != nil {
		return m.ExtraData
	}
	return ""
}

func (m *Blockchain) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Blockchain) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *Blockchain) GetGasUsed() string {
	if m != nil {
		return m.GasUsed
	}
	return ""
}

func (m *Blockchain) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Blockchain) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Blockchain) GetUncles() []string {
	if m != nil {
		return m.Uncles
	}
	return nil
}

type Transaction struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BlockHash            string   `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber          string   `protobuf:"bytes,4,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TransactionIndex     string   `protobuf:"bytes,5,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	From                 string   `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	Value                string   `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	GasPrice             string   `protobuf:"bytes,9,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Gas                  string   `protobuf:"bytes,10,opt,name=gas,proto3" json:"gas,omitempty"`
	Input                string   `protobuf:"bytes,11,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40374cd18fa609d, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Transaction) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Transaction) GetTransactionIndex() string {
	if m != nil {
		return m.TransactionIndex
	}
	return ""
}

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Transaction) GetGas() string {
	if m != nil {
		return m.Gas
	}
	return ""
}

func (m *Transaction) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type TransactionReceipt struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNumber          string   `protobuf:"bytes,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TransactionIndex     string   `protobuf:"bytes,4,opt,name=transactionIndex,proto3" json:"transactionIndex,omitempty"`
	CumulativeGasUsed    string   `protobuf:"bytes,5,opt,name=cumulativeGasUsed,proto3" json:"cumulativeGasUsed,omitempty"`
	GasUsed              string   `protobuf:"bytes,6,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	ContractAddress      string   `protobuf:"bytes,7,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	LogsBloom            string   `protobuf:"bytes,8,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40374cd18fa609d, []int{2}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *TransactionReceipt) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *TransactionReceipt) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *TransactionReceipt) GetTransactionIndex() string {
	if m != nil {
		return m.TransactionIndex
	}
	return ""
}

func (m *TransactionReceipt) GetCumulativeGasUsed() string {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return ""
}

func (m *TransactionReceipt) GetGasUsed() string {
	if m != nil {
		return m.GasUsed
	}
	return ""
}

func (m *TransactionReceipt) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *TransactionReceipt) GetLogsBloom() string {
	if m != nil {
		return m.LogsBloom
	}
	return ""
}

func (m *TransactionReceipt) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Blockchain)(nil), "eth.Blockchain")
	proto.RegisterType((*Transaction)(nil), "eth.Transaction")
	proto.RegisterType((*TransactionReceipt)(nil), "eth.TransactionReceipt")
}

func init() { proto.RegisterFile("eth/eth.proto", fileDescriptor_c40374cd18fa609d) }

var fileDescriptor_c40374cd18fa609d = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xd5, 0xa4, 0xeb, 0xda, 0xd3, 0x6e, 0xed, 0x0c, 0x9a, 0x2c, 0x34, 0xa1, 0xaa, 0x57,
	0x15, 0x42, 0x2d, 0x62, 0xbc, 0x00, 0xd5, 0x24, 0x86, 0x84, 0x10, 0x2a, 0xec, 0x86, 0x3b, 0xd7,
	0x71, 0x13, 0x8b, 0xc4, 0xae, 0xe2, 0x93, 0x69, 0xf0, 0x36, 0xbc, 0x12, 0x17, 0x3c, 0x0f, 0xf2,
	0x1f, 0x92, 0xb4, 0x15, 0x62, 0x77, 0xfe, 0xbe, 0x73, 0xec, 0xd8, 0x9f, 0x7f, 0x31, 0x9c, 0x09,
	0xcc, 0x96, 0x02, 0xb3, 0xc5, 0xae, 0xd4, 0xa8, 0x49, 0x2c, 0x30, 0x9b, 0xfd, 0xee, 0x02, 0xac,
	0x72, 0xcd, 0xbf, 0xf1, 0x8c, 0x49, 0x45, 0x9e, 0x03, 0xa8, 0xaa, 0xd8, 0x88, 0xf2, 0xb3, 0xfc,
	0x21, 0x68, 0x67, 0xda, 0x99, 0x0f, 0xd6, 0x2d, 0x87, 0x10, 0xe8, 0x66, 0xcc, 0x64, 0x34, 0x72,
	0x15, 0x37, 0xb6, 0x73, 0x76, 0xac, 0x14, 0x0a, 0x6f, 0x6d, 0x25, 0xf6, 0x73, 0x1a, 0x87, 0x3c,
	0x85, 0x13, 0xa5, 0x15, 0x17, 0xb4, 0xeb, 0x4a, 0x5e, 0xd8, 0x59, 0x26, 0x63, 0xd7, 0x77, 0x8a,
	0xe7, 0xc2, 0xd0, 0x13, 0x3f, 0xab, 0x71, 0xc8, 0x15, 0x0c, 0x72, 0x9d, 0x9a, 0x55, 0xae, 0x75,
	0x41, 0x7b, 0xae, 0xdc, 0x18, 0xe4, 0x05, 0x4c, 0xb0, 0x64, 0xca, 0x30, 0x8e, 0x52, 0x2b, 0xb3,
	0xd6, 0x1a, 0xe9, 0xa9, 0x6b, 0x3a, 0xf2, 0xed, 0x4a, 0x06, 0x19, 0x0a, 0xd7, 0xd4, 0xf7, 0x2b,
	0xd5, 0x06, 0x99, 0xc1, 0xa8, 0x14, 0x5c, 0xc8, 0x1d, 0xfa, 0x55, 0x06, 0xae, 0x61, 0xcf, 0xb3,
	0x27, 0x28, 0xa4, 0x12, 0x25, 0x05, 0x7f, 0x02, 0x27, 0xec, 0x09, 0x12, 0xb9, 0xdd, 0x4a, 0x5e,
	0xe5, 0xf8, 0x9d, 0x0e, 0xfd, 0x09, 0x1a, 0x87, 0xcc, 0x61, 0x8c, 0x1a, 0x59, 0x7e, 0xd3, 0x34,
	0x8d, 0x5c, 0xd3, 0xa1, 0x6d, 0x77, 0x28, 0x1e, 0xb0, 0x64, 0x37, 0x0c, 0x19, 0x3d, 0xf3, 0x3b,
	0xac, 0x0d, 0x9b, 0xb9, 0xb1, 0xb7, 0x71, 0xee, 0x33, 0xb7, 0x63, 0xf2, 0x0c, 0xfa, 0x29, 0x33,
	0x1f, 0x64, 0x21, 0x91, 0x8e, 0x9d, 0x5f, 0x6b, 0x42, 0xe1, 0x34, 0x65, 0xe6, 0xce, 0x88, 0x84,
	0x4e, 0x5c, 0xe9, 0xaf, 0xb4, 0xdf, 0x41, 0x59, 0x08, 0x83, 0xac, 0xd8, 0xd1, 0x0b, 0xff, 0x9d,
	0xda, 0x20, 0x6f, 0x60, 0xd4, 0xce, 0x8e, 0x92, 0x69, 0x3c, 0x1f, 0xbe, 0x9e, 0x2c, 0x2c, 0x31,
	0x5f, 0x9a, 0xc2, 0x7a, 0xaf, 0x8b, 0x5c, 0x42, 0xaf, 0xf2, 0x77, 0xf8, 0x64, 0x1a, 0xcf, 0x07,
	0xeb, 0xa0, 0x66, 0x3f, 0x23, 0x18, 0xb6, 0x66, 0xd5, 0xe4, 0x74, 0x5a, 0xe4, 0xd4, 0x64, 0x44,
	0x6d, 0x32, 0xae, 0x60, 0xb0, 0xb1, 0x44, 0xb6, 0x70, 0x6a, 0x0c, 0x32, 0x85, 0xa1, 0x13, 0x1f,
	0x1d, 0x94, 0x81, 0xa9, 0xb6, 0x75, 0xc0, 0xc6, 0x7b, 0x95, 0x88, 0x87, 0xc0, 0xd7, 0x91, 0x6f,
	0x77, 0xb5, 0x2d, 0x6b, 0xc0, 0xdc, 0x98, 0x9c, 0x43, 0x84, 0x3a, 0xd0, 0x14, 0xa1, 0xb6, 0xbb,
	0xbc, 0x67, 0x79, 0x25, 0x02, 0x3b, 0x5e, 0x84, 0x1b, 0xf8, 0x54, 0x4a, 0x2e, 0x02, 0x33, 0xb5,
	0x26, 0x13, 0x88, 0x53, 0x66, 0x02, 0x2d, 0x76, 0x68, 0xd7, 0x90, 0x6a, 0x57, 0x61, 0xc0, 0xc4,
	0x8b, 0xd9, 0xaf, 0x08, 0x48, 0x3b, 0x59, 0xcf, 0x9c, 0x03, 0xa7, 0x71, 0x6f, 0x9b, 0xd4, 0x0e,
	0xed, 0xfd, 0xa8, 0xa2, 0xff, 0x44, 0x15, 0x3f, 0x2e, 0xaa, 0xee, 0x3f, 0xa2, 0x7a, 0x09, 0x17,
	0xbc, 0x2a, 0xaa, 0x9c, 0xa1, 0xbc, 0x17, 0xef, 0x02, 0x60, 0x3e, 0xd7, 0xe3, 0x42, 0x1b, 0xc2,
	0xde, 0x3e, 0x84, 0x73, 0x18, 0x73, 0xad, 0xb0, 0x64, 0x1c, 0xdf, 0x26, 0x49, 0x29, 0x8c, 0x09,
	0x59, 0x1f, 0xda, 0xfb, 0x4f, 0x40, 0xff, 0xf0, 0x09, 0xb8, 0x84, 0x9e, 0xfd, 0x8b, 0x2b, 0x13,
	0xe2, 0x0f, 0x6a, 0xf5, 0xea, 0xeb, 0x22, 0x95, 0x98, 0x55, 0x9b, 0x05, 0xd7, 0xc5, 0xd2, 0x9d,
	0x56, 0x2a, 0x23, 0xd3, 0x0c, 0x97, 0x85, 0x4e, 0x44, 0xee, 0x5f, 0xbf, 0x65, 0xaa, 0x73, 0xa6,
	0x52, 0xfb, 0x1c, 0x6e, 0x7a, 0xce, 0xb9, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x9a, 0x6f,
	0x8f, 0x20, 0x05, 0x00, 0x00,
}
